// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8UEkQR3KK737oDoaqqtzWHVGsm-5JNUY',
    appId: '1:257241274606:android:e02e59d23fb74f5799fbff',
    messagingSenderId: '257241274606',
    projectId: 'detektive-3e367',
    databaseURL: 'https://detektive-3e367-default-rtdb.firebaseio.com',
    storageBucket: 'detektive-3e367.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKHyVTpdZ4ZKdlNGPTIUYVhR4s2WhyAJc',
    appId: '1:257241274606:ios:aecb4726ea35ed0099fbff',
    messagingSenderId: '257241274606',
    projectId: 'detektive-3e367',
    databaseURL: 'https://detektive-3e367-default-rtdb.firebaseio.com',
    storageBucket: 'detektive-3e367.appspot.com',
    androidClientId: '257241274606-3adlbef5jtdue9sc47d2oj1qbfm838gg.apps.googleusercontent.com',
    iosClientId: '257241274606-cv3co2klg02riscqs46fqlen13fmii2q.apps.googleusercontent.com',
    iosBundleId: 'com.hiennv.testing',
  );
}
